### ISSUE TITLE
Make the change method the default and comment out up/down

### ISSUE THREAD

**Issue by robmorgan** [robmorgan/phinx#287]
This is potentially a big change moving forwards.

In newly created migrations `up` and `down` would be commented out by default and `change` would become the default method.

This is the opposite of the present behaviour.

#### Background
The `change` method is far simpler to use and suffices for most users. The `up` /  `down` methods are more flexible but should be used less.

**Comment by evought** [comment]
Does change() work correctly with data migration, not just schema migration? In other words, if I modify a column in a table and have to adjust existing rows based on a SELECT, won't I have to create a custom down() method? Or if I drop a table/column in a migration and need to recreate it on rollback? Of course, you are just talking about changing the default here and I will still be able to override it by creating an up()/down() method when I need it?

I am looking at moving to phinx on a project and am trying to understand what the approximate limits are to understand the impact of planned changes and how I should organize my initial setup.

**Comment by shadowhand** [comment]
@evought see the note about limitations at the end of http://docs.phinx.org/en/latest/migrations.html#the-change-method

**Comment by evought** [comment]
"see the note about limitations..."

Understood, thank you. Been experimenting with the behavior this evening and it seems fairly logical.

**Comment by RQuadling** [comment]
With regard to the current state, and the proposal to make ```change()``` the default operation, would it be advantageous (and more defensive) to validate that the migration can be rolled-back BEFORE the migration takes place? Maybe by using a variant of the adapters that only allow the reversible methods?

So, ```up()``` and ```down()``` would use the current adapter and I am at will to do whatever I want.

But ```change()``` would use a limited adapter that simply does not have any method that cannot be reversed.

For me, the advantage here is that the developer is protected from making non-reversible mistakes. Make their/our lives easier.

**Comment by robmorgan** [comment]
Hey @RQuadling I'd prefer to keep Phinx as dumb as possible. Some people run Phinx on massive production systems with 100's of tables and terrabytes of data. I'd sleep much better knowing they are in full control of their migrations (even if they write something nasty). If Phinx started to become opinionated about migrations I'm worried it might lead to problems. Better to keep it simple.

**Comment by robmorgan** [comment]
p.s moving to 0.5.0 now.

**Comment by maxgalbu** [comment]
I agree with @RQuadling, those people would not have full control on their migration because they would unknowingly make a change in the change() method that can't be reverted. The full control is having up() and down() and being able to make mistakes because of my code and not phinx's.

**Comment by RQuadling** [comment]
What I was saying is that the methods that can be called in the ```change()``` method should be limited to reversible ones. If a user requires something that cannot be automatically reversed in a migration then they need to use ```up()``` and ```down()```.

**Comment by robmorgan** [comment]
done in 5ffb2324f5789c8919271dd2c6bb0b448a0b02a1

**Comment by rquadling** [comment]
I suppose we need to see a use case of a non reversible ``change()`` call. I'm still not sure that every use of change IS reversible.

``up()``/``down()`` *IS* the "in the hands of the developer" control that is required.

On the other hand, I never use ``change()``, so meh!
