### ISSUE TITLE
MySQL error when running migrations for the first time, i.e. creating the phinx_log table

### ISSUE THREAD

**Issue by stephenmelrose** [robmorgan/phinx#531]
Hi,

I'm getting the following output/error when running Phinx for the first time on a freshly built server,

    [InvalidArgumentException]
    There was a problem creating the schema table: SQLSTATE[HY000]: General error: 1293 Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause

Looking at my local copy (that doesn't produce the error), I assume this to do with the phinx_log table.

I'm running the following versions,

    PHP 5.5.9-1ubuntu4.7 (cli)
    Phinx by Rob Morgan - https://phinx.org. version 0.4.2.1
    MySQL Server 5.5.41-0ubuntu0.14.04.1 (Ubuntu)

**Comment by stephenmelrose** [comment]
Ignore me. Fixed in `0.4.3`.

**Comment by Djumpen** [comment]
This still occurs to me

PHP 5.5.9-1ubuntu4.19 
Phinx by Rob Morgan - https://phinx.org. version 0.6.4
MySQL Server'5.5.50-0ubuntu0.14.04.1

**Comment by rquadling** [comment]
http://stackoverflow.com/questions/4489548/why-there-can-be-only-one-timestamp-column-with-current-timestamp-in-default-cla/17498167#17498167

http://dev.mysql.com/doc/relnotes/mysql/5.6/en/news-5-6-5.html

http://dev.mysql.com/doc/refman/5.6/en/timestamp-initialization.html

**Comment by Djumpen** [comment]
Thanks, Mysql 5.6 solves the problem

**Comment by rquadling** [comment]
No problem. Hopefully a painless upgrade.
